name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Debug Inputs
        run: echo "Repository Owner: ${{ github.repository_owner }}"

      - uses: Platane/snk@v2
        with:
          github_user_name: Swaggie190
          outputs: dist/github-snake.svg

      - name: Verify Generated Files
        run: ls -la dist

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
